api6/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

#namespace
app_name='home'

urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.loginUser,name='login'),
    path('post/',views.addpost,name='post'),
    path('logout/',views.logoutUser,name='logout'),
    path('posts/author/',views.get_post_by_username,name='post_author'),
    path('posts/archive/monthly/',views.get_post_by_date,name='post_month'),
    path('posts/archive/yearly/',views.get_post_by_year,name='post_year'),
    path('posts/id/<str:key>/',views.get_id,name='post_id'),
    path('contactus/',views.contactus,name='contactus'),
]

home/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class post(models.Model):
    title=models.CharField(max_length=150)
    content=models.TextField()
    timestamp=models.DateTimeField(default=timezone.now())         #post date
    posted_by=models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.title +' by '+str(self.posted_by)

class contact(models.Model):
    name=models.CharField(max_length=150)
    email=models.EmailField()
    message=models.TextField()
    timestamp=models.DateTimeField(default=timezone.now())         #post date
    def __str__(self):
        return self.name

home/forms.py
from django.forms import ModelForm
from .models import *

# class ContactForm(forms.Form):
#     name=forms.CharField(max_length=50)
#     email=forms.EmailField()
#     text=forms.CharField(max_length=1000,widget=forms.Textarea)

class ContactForm(ModelForm):
    class Meta:
        model=contact
        fields=['name','email','message']

home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .models import post
from .forms import *


def signup(req):
    if req.method=='POST':
        new_user=User.objects.create_user(
            username=req.POST.get('username'),
            email=req.POST.get('email'),
            password=req.POST.get('password'),
            first_name=req.POST.get('fname'),
            last_name=req.POST.get('lname'))
        return redirect('home:login')
    else:
        return render(req,'home/signup.html')

def loginUser(req):
    if req.method=='POST':
        user=authenticate(username=req.POST.get('username'),
        password=req.POST.get('password'))
        if user:
            login(req,user)
            return redirect('home:post')
        else:
            return HttpResponse('Invalid credentials or Access Blocked!')
    else:
        return render(req,'home/login.html')

@login_required
def addpost(req):
    if req.method=='POST':
        new_post=post()
        new_post.title=req.POST.get('title')
        new_post.content=req.POST.get('content')
        new_post.posted_by=req.user
        new_post.save()
        return redirect('home:index')
    else:
        return render(req,'home/post.html',{'data':req.user})

@login_required
def logoutUser(req):
    logout(req)
    return redirect('home:login')

def index(req):
    posts=post.objects.all()
    return render(req,'home/index.html',{'posts':posts})

def get_post_by_username(req):
    user=User.objects.get(username=req.GET['name'])
    posts=post.objects.filter(posted_by=user)
    return render(req,'home/index.html',{'posts':posts})

def get_post_by_date(req):
    month=req.GET['month']
    year=req.GET['year']
    print(month,year)
    posts=post.objects.filter(timestamp__month=month,timestamp__year=year)
    return render(req,'home/index.html',{'posts':posts})



def get_post_by_year(req):
    year=req.GET['year']
    posts=post.objects.filter(timestamp__year=year)
    return render(req,'home/index.html',{'posts':posts})

def get_id(req,key):
    posts=post.objects.filter(id=key)
    return render(req,'home/index.html',{'posts':posts})

def contactus(req):
    if req.method=='POST':
        form=ContactForm(req.POST)
        if form.is_valid():
            name=form.cleaned_data['name']
            email=form.cleaned_data['email']
            message=form.cleaned_data['message']
            print(name,email,message)
            return HttpResponse('success')
    else:
        form=ContactForm()    
        return render(req,'home/contactus.html',{'data':req.user,'form':form})

home/templates/home/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static "home/css/index.css" %}">

   <title> {% block title %}   {% endblock  %}</title>
  </head>
  <body>
<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:index' %}">Blogsite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=#>Welcome {{data}} </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "home:contactus" %}">Contact Us</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:logout' %}">Log Out </a>
      </li>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class= "container-fluid">
{% block content %}

{% endblock  %}
</div>
 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

home/templates/home/contactus.html
{% extends "home/base.html" %}


{% block title %}
Contact Us | Blogsite
{% endblock  %}

{% block  content%}
<form method="POST" action="" class="register">
  {% csrf_token %}

  {{form}}
  <input type="submit" value="Submit">
</form>
{% endblock %}

  	

home/templates/home/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static "home/css/index.css" %}">

    <title>Blogsite | Posts</title>
  </head>
  <body>
<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Blogsite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:signup' %}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:login' %}">Log in</a>
      </li>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<!--navbar-->
  <div class='container-fluid' class='apost' >
  
 {% for post  in posts  %}


<div class="card"  style="width: 100%; margin:2px; background-color:#d1d1d1; ">
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Posted By : {{post.posted_by}}</h6>
    <p class="card-text">{{post.content}}</p>
    </div>
</div>
{% endfor %}
  		
  	</div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static "home/css/index.css" %}">

    <title>Blogsite | Login</title>
  </head>
  <body>
<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:index' %}">Blogsite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:signup' %}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:login' %}">Log in <span class="sr-only">(current)</span></a>
      </li>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<!--navbar-->
<center>
  <div class="container-fluid">
    <form method="POST" action="/login/" class="register">
    {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Username</label>
    <input class="form-control" id="exampleInputEmail1"  name="username" type="text" placeholder="Username" required>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

Do not have a account?<a href={% url 'home:signup' %}>Sign Up</a>
  	</div>
</center> 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/post.html
{% extends "home/base.html" %}
{% block title %}
Post | Blogsite
{% endblock %}

{% block content %}
<center>
  <div class="container-fluid">
    <form method="POST" action="/post/" class="register">
    <center><h2>Add your Post {{data}}</h2></center>
    {% csrf_token %}
  <div class="form-group">
    <label for="formGroupExampleInput">Title</label>
    <input type="text" name="title" class="form-control" id="formGroupExampleInput" placeholder="Title" required>
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">Content</label>
    <textarea name="content" class="form-control" id="formGroupExampleInput2"rows="5" placeholder="Content" required></textarea>
  </div>
     <button type="submit" class="btn btn-primary">Submit</button>

</form>

</center> 
{% endblock  %}


  

home/templates/home/signup.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static "home/css/index.css" %}">

    <title>Blogsite | Sign-Up</title>
  </head>
  <body>
<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:index' %}">Blogsite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:signup' %}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:login' %}">Log in <span class="sr-only">(current)</span></a>
      </li>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<!--navbar-->
<center>
  <div class="container-fluid">
    <form method="POST" action="/signup/" class="register">
    {% csrf_token %}
  <div class="form-group" >
    <label for="formGroupExampleInput">Email ID</label>
    <input type="email" name="email" class="form-control" id="formGroupExampleInput" placeholder="Email  ID" required>
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">First Name</label>
    <input type="text" name="fname" class="form-control" id="formGroupExampleInput2" placeholder="First Name" required>
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput3">Last Name</label>
    <input type="text" name="lname" class="form-control" id="formGroupExampleInput3" placeholder="Last Name" required>
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput4">Username</label>
    <input type="text" name="username" class="form-control" id="formGroupExampleInput4" placeholder="Username" required>
  </div>
    <div class="form-group">
    <label for="formGroupExampleInput5">Password</label>
    <input type="password" name="password" class="form-control" id="formGroupExampleInput3" placeholder="Password" required>
  </div>
     <button type="submit" class="btn btn-primary">Submit</button>

</form>

Already have a account?<a href={% url 'home:login' %}>Log In</a>
  	</div>
</center> 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>